[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
rand = "0.9.2"
wasm-bindgen = "0.2"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"

[lib]
crate-type = ["cdylib"]